import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/orders" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Orders
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/profile" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Profile
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/becomeseller" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BecomeSeller
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePage
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Signin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signup" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SignUp
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/fqa" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FQA
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/store" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Store
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/productdetail" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Productdetail
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/card" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Card
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/confirmpayment" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ConfirmPayment
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/order" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Order
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/productdetailone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProductdetailOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/admin" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Admin
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/dasboard" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Dasboard
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/cart" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Cart
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/productdetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProductDetails
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/mainsection" style={{ color: "#87CEFA", textDecoration: "none" }}>
            MainSection
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/desktopone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            DesktopOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/ordercard" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Ordercard
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/footer2" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Footer2
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/profileone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProfileOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/mainsectionone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            MainSectionOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/frame936" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Frame936
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/profilethree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProfileThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/profilefour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProfileFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/storeone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            StoreOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepageone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePageOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/ordersone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            OrdersOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePageTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/productdetailsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ProductDetailsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/confirmpaymentone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ConfirmPaymentOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/cartone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            CartOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/becomesellerone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            BecomeSellerOne
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
